default: &default
  adapter: postgresql
  encoding: unicode
  username: stylist
  password: generic26
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: stylist_development

test:
  <<: *default
  database: stylist_test

production:
  <<: *default
  database: stylist_production
  username: stylist
  password: <%= ENV['STYLIST_DATABASE_PASSWORD'] %>
